"""Plain-language component labels for the architecture diagram.

Labels are generated by Claude and cached on disk keyed by a content fingerprint,
so a component is only re-described when its code actually changes.
"""
import json
from pathlib import Path
from typing import Dict

import anthropic

from .quiz import HAIKU_MODEL


async def generate_component_label(component: Dict, client) -> str:
    """One short sentence describing what a component (file) does."""
    fn_names = ", ".join(f["name"] for f in component["functions"][:30]) or "(no functions)"
    prompt = (
        f"This is a source file named `{component['name']}` in a codebase. It defines: "
        f"{fn_names}.\n\nIn ONE short sentence (no preamble), describe what this file is "
        f"responsible for. Reply with the sentence only."
    )
    try:
        resp = await client.messages.create(
            model=HAIKU_MODEL,
            max_tokens=80,
            messages=[{"role": "user", "content": prompt}],
        )
    except anthropic.APIError:
        return ""
    return resp.content[0].text.strip()


def _load_cache(cache_path: Path) -> Dict:
    try:
        return json.loads(cache_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _save_cache(cache_path: Path, cache: Dict) -> None:
    try:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        cache_path.write_text(json.dumps(cache, indent=2), encoding="utf-8")
    except OSError:
        pass


async def attach_component_labels(diagram: Dict, cache_path: Path, client) -> Dict:
    """Fill each component's ``label``, generating only for changed components."""
    cache = _load_cache(cache_path)
    for comp in diagram["components"]:
        fp = comp.get("fingerprint")
        cached = cache.get(comp["id"])
        if cached and cached.get("fingerprint") == fp:
            comp["label"] = cached["label"]
            continue
        label = await generate_component_label(comp, client)
        comp["label"] = label
        cache[comp["id"]] = {"fingerprint": fp, "label": label}
    _save_cache(cache_path, cache)
    return diagram
