"""Plain-language component labels for the architecture diagram.

Labels are generated by Claude and cached on disk keyed by a content fingerprint,
so a component is only re-described when its code actually changes.
"""
import json
from pathlib import Path
from typing import Dict

import anthropic

from .quiz import HAIKU_MODEL


def _looks_like_a_question(text: str) -> bool:
    """A description shouldn't be a question — that means the model asked for input
    (e.g. "could you share the source?") instead of describing the file."""
    return not text or text.rstrip().endswith("?")


def _function_listing(component: Dict) -> str:
    lines = []
    for f in component["functions"][:30]:
        sig = f.get("signature") or f["name"]
        doc = (f.get("docstring") or "").strip().splitlines()
        first = f"  # {doc[0]}" if doc else ""
        lines.append(f"- {sig}{first}")
    return "\n".join(lines) or "(no functions)"


async def generate_component_label(component: Dict, client) -> str:
    """One short sentence describing what a component (file) does."""
    prompt = (
        f"A source file named `{component['name']}` defines these functions "
        f"(signatures, with a docstring line where present):\n"
        f"{_function_listing(component)}\n\n"
        f"From the names and signatures alone, infer what this file is responsible for. "
        f"Reply with ONE short declarative sentence and nothing else. Do NOT ask for the "
        f"source code or say you lack information; give your best inference."
    )
    try:
        resp = await client.messages.create(
            model=HAIKU_MODEL,
            max_tokens=80,
            messages=[{"role": "user", "content": prompt}],
        )
    except anthropic.APIError:
        return ""
    text = resp.content[0].text.strip()
    return "" if _looks_like_a_question(text) else text


def _load_cache(cache_path: Path) -> Dict:
    try:
        return json.loads(cache_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _save_cache(cache_path: Path, cache: Dict) -> None:
    try:
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        cache_path.write_text(json.dumps(cache, indent=2), encoding="utf-8")
    except OSError:
        pass


async def attach_component_labels(diagram: Dict, cache_path: Path, client) -> Dict:
    """Fill each component's ``label``, generating only for changed components."""
    cache = _load_cache(cache_path)
    for comp in diagram["components"]:
        fp = comp.get("fingerprint")
        cached = cache.get(comp["id"])
        if cached and cached.get("fingerprint") == fp:
            comp["label"] = cached["label"]
            continue
        label = await generate_component_label(comp, client)
        comp["label"] = label
        cache[comp["id"]] = {"fingerprint": fp, "label": label}
    _save_cache(cache_path, cache)
    return diagram
