"""Plain-language component labels for the architecture diagram.

Labels are generated by Claude and cached on disk keyed by a content fingerprint,
so a component is only re-described when its code actually changes.
"""
from pathlib import Path
from typing import Dict

# Stub — implemented in the green commit.


async def generate_component_label(component: Dict, client) -> str:
    return ""


async def attach_component_labels(diagram: Dict, cache_path: Path, client) -> Dict:
    return diagram
